#! /bin/bash

xinput set-prop "MSFT0001:00 06CB:7E7E Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "MSFT0001:00 06CB:7E7E Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "MSFT0001:00 06CB:7E7E Touchpad" "libinput Natural Scrolling Enabled" 1

setxkbmap -model pc104 -layout us,gr -option 'grp:win_space_toggle'

killall picom
picom --config $HOME/.local/dwm/picom.conf &
killall nitrogen
nitrogen --restore

checkupdates &
sleep 1s && bash $HOME/.local/dwm/statusbar &

xset s off -dpms

export _JAVA_AWT_WM_NONREPARENTING=1

