#! /bin/bash

while true; do
	VOLUME=""
	if [ "$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2};')" == "yes" ]; then
		VOLUME=" MUTE "
	else
		VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F "/" '{print $2};')
	fi

	BAT_ICON=$(cat /sys/class/power_supply/BAT0/status)
	if [ "$BAT_ICON" == "Charging" ]; then
		BAT_ICON="^"
	elif [ "$BAT_ICON" == "Full" ]; then
		BAT_ICON="-"
	else
		BAT_ICON="v"
	fi
	BAT=$(cat /sys/class/power_supply/BAT0/capacity)

	NETWORK=$(nmcli | grep wlp2s0 | grep -v disconnected | grep -c connected)
	if [ "$NETWORK" == "0" ]; then
		NETWORK="N/NET"
	else
		NETWORK="NET"
	fi

	LANG=$(xkblayout-state print "%s")

	TIME=$(date +'%x %R')

	UPDATES=$(checkupdates --nosync | wc -l)

	xsetroot -name " $BAT_ICON $BAT% |$VOLUME| $LANG | $NETWORK | upd:$UPDATES | $TIME "
	echo " $BAT_ICON $BAT% |$VOLUME| $LANG | $NETWORK | upd:$UPDATES | $TIME "
	sleep 3s
done
